/**
 * @file Version.h
 * @brief Version information for LDC1614.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef LDC1614_VERSION_STRING
#define LDC1614_VERSION_STRING "3.0.0"
#endif

#ifndef LDC1614_BUILD_DATE
#define LDC1614_BUILD_DATE "unknown-date"
#endif

#ifndef LDC1614_BUILD_TIME
#define LDC1614_BUILD_TIME "unknown-time"
#endif

#ifndef LDC1614_BUILD_TIMESTAMP
#define LDC1614_BUILD_TIMESTAMP LDC1614_BUILD_DATE " " LDC1614_BUILD_TIME
#endif

#ifndef LDC1614_GIT_COMMIT
#define LDC1614_GIT_COMMIT "unknown"
#endif

#ifndef LDC1614_GIT_STATUS
#define LDC1614_GIT_STATUS "unknown"
#endif

#ifndef LDC1614_VERSION_FULL
#define LDC1614_VERSION_FULL LDC1614_VERSION_STRING " (" LDC1614_GIT_COMMIT ", " LDC1614_BUILD_TIMESTAMP ", " LDC1614_GIT_STATUS ")"
#endif

namespace LDC1614 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 3;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = LDC1614_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 30000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 30000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = LDC1614_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = LDC1614_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = LDC1614_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = LDC1614_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = LDC1614_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = LDC1614_VERSION_FULL;

}  // namespace LDC1614
